version: '3.8'  # Specifies the Docker Compose file version
services:
  mongo:  # MongoDB service
    image: mongo:5.0  # Uses the official MongoDB version 5.0 image
    container_name: mongodb  # Name of the container
    ports:
      - "27017:27017"  # Maps the host port 27017 to container port 27017
    environment:
      MONGO_INITDB_DATABASE: PetCare  # Sets the default database name

  flask-app:  # Flask application service
    build:
      context: .  # Specifies the current directory as the build context
    container_name: flask-app  # Name of the container
    ports:
      - "5000:5000"  # Maps the host port 5000 to container port 5000
    environment:
      - DB_HOST=mongo  # Sets the MongoDB host to the 'mongo' service
      - DB_NAME=PetCare  # Sets the database name
      - DB_PORT=27017  # Sets the MongoDB port
    depends_on:
      - mongo  # Ensures MongoDB starts before the Flask app